//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.JqGrid.JqGridDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer_ProductsDetail
    {
        public System.Guid KID { get; set; }
        public string SkuNo { get; set; }
        public string Offer_ProductsProductNo { get; set; }
        public string Offer_ProducrColorCode { get; set; }
        public string Offer_ProductSizeCode { get; set; }
        public string Offier_ProductUnitCode { get; set; }
        public string SkuBarCode { get; set; }
        public Nullable<decimal> SkuWeight { get; set; }
        public Nullable<decimal> SkuLength { get; set; }
        public Nullable<decimal> SkuWidth { get; set; }
        public Nullable<decimal> SkuHeight { get; set; }
        public Nullable<decimal> SkuMarketPrice { get; set; }
        public Nullable<decimal> SkuWholeSalePrice { get; set; }
        public Nullable<decimal> SkuPurchasePrice { get; set; }
        public string IsSalePaking { get; set; }
        public string IsIntergral { get; set; }
        public string Del { get; set; }
        public string State { get; set; }
        public Nullable<int> Version { get; set; }
        public string IsNew { get; set; }
        public string IsHot { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public string DefaultImage { get; set; }
        public string ProductSkuName { get; set; }
        public Nullable<System.DateTime> UpDate { get; set; }
        public Nullable<int> SaleNumber { get; set; }
        public int AutogRowID { get; set; }
    }
}
